apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: example-namespace
  labels:
    app.kubernetes.io/managed-by: tekton-pipeline
    app.kubernetes.io/created-by: user123
  annotations:
    pipeline.tekton.dev/created-by: user123kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: test-ns-6
  annotations:
    openshift.io/requester: 123
    apps.open-cluster-management.io/do-not-delete: 'true'
spec:
  hard:
    requests.cpu: 10
    limits.cpu: 30
    pods: 20
    requests.memory: 2Gi
    limits.memory: 4Gi
  scopes:
    - NotTerminating