apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: example-project
  annotations:
    openshift.io/display-name: "Example Project"
    openshift.io/description: "Project for workloads with resource quotas and limit ranges"

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: example-resource-quota
  namespace: example-project
spec:
  hard:
    cpu: "4"
    memory: 16Gi
    pods: "20"
    services: "10"
    persistentvolumeclaims: "10"
    configmaps: "20"
    secrets: "20"

---
apiVersion: v1
kind: LimitRange
metadata:
  name: example-limit-range
  namespace: example-project
spec:
  limits:
    - type: Container
      max:
        cpu: "2"
        memory: 8Gi
      min:
        cpu: "100m"
        memory: 128Mi
      default:
        cpu: "500m"
        memory: 512Mi
      defaultRequest:
        cpu: "200m"
        memory: 256Mi
