apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline-source-workspace
  namespace: openshift-pipelines
  labels:
    app.kubernetes.io/name: openshift-pipelines
    app.kubernetes.io/component: workspace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3-csi  # Adjust based on your cluster's available storage classes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline-output-workspace
  namespace: openshift-pipelines
  labels:
    app.kubernetes.io/name: openshift-pipelines
    app.kubernetes.io/component: workspace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp3-csi  # Adjust based on your cluster's available storage classes
