# Git Credentials Secret Template
# Replace the values with actual credentials before applying
apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: openshift-pipelines
  labels:
    app.kubernetes.io/name: openshift-pipelines
    app.kubernetes.io/component: git-auth
  annotations:
    tekton.dev/git-0: https://github.com  # Git server URL
type: kubernetes.io/basic-auth
stringData:
  username: YOUR_GITHUB_USERNAME  # Replace with actual GitHub username
  password: YOUR_GITHUB_TOKEN     # Replace with actual GitHub personal access token
---
# Alternative: SSH key-based authentication
apiVersion: v1
kind: Secret
metadata:
  name: git-ssh-credentials
  namespace: openshift-pipelines
  labels:
    app.kubernetes.io/name: openshift-pipelines
    app.kubernetes.io/component: git-auth
  annotations:
    tekton.dev/git-0: git@github.com
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    # Replace with your actual SSH private key
    -----END OPENSSH PRIVATE KEY-----
  known_hosts: |
    # Replace with your git server's known hosts entry
    # You can get this by running: ssh-keyscan github.com
